### PR TITLE
Issue#2 run script

### PR DESCRIPTION
**Pull request by JR-Utily**
Here is the way I use this docker

### CODE REVIEW

**Comment by aviggiano** [comment]
Thank you for the PR! Awesome documentation.
I'll test it locally and give feedback if I have any issues.

**Comment by aviggiano** [comment]
Hi again. I followed the instructions on the README and they are pretty clear, but I am unable to download the GP6 soundbanks.
Did you input your KEY ID with spaces? 

I'll merge this anyway and give it a try later

**Comment by JR-Utily** [comment]
My KEY ID is something like XXXXX-YYYYY-ZZZZZ
I did buy extra soundbanks some years ago, and everything was in the GPUpdater GUI

**Comment by JR-Utily** [comment]
If it doesn't work, maybe there is another solution. In the shell:
 - start GuitarPro, enter the credentials
- close it
- start GPUpdater, I think it will not ask again for credentials if they were entered before

**Pull request merged**
